# Generated by Django 4.2 on 2023-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
