# Generated by Django 4.2.4 on 2023-08-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
