# Generated by Django 4.2.4 on 2023-08-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
