# Generated by Django 4.2.4 on 2023-08-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0, verbose_name='Product Count'),
        ),
    ]
