# Generated by Django 4.2.4 on 2023-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_count',
        ),
    ]
